var test = require('tape')
var name = require('../../lib/duration/name')

test('duration name', function (t) {
  t.equal(name(4), 'l')
  t.equal(name(4 + 2), 'l.')
  t.equal(name(4 + 2 + 1), 'l..')
  t.equal(name(2), 'd')
  t.equal(name(2 + 1), 'd.')
  t.equal(name(2 + 1 + 1 / 2), 'd..')
  t.equal(name(1), 'w')
  t.equal(name(1 + 1 / 2), 'w.')
  t.equal(name(1 + 1 / 2 + 1 / 4), 'w..')
  t.equal(name(1 / 2), 'h')
  t.equal(name(1 / 2 + 1 / 4), 'h.')
  t.equal(name(1 / 2 + 1 / 4 + 1 / 8), 'h..')
  t.equal(name(1 / 4), 'q')
  t.equal(name(1 / 4 + 1 / 8), 'q.')
  t.equal(name(1 / 4 + 1 / 8 + 1 / 16), 'q..')
  t.equal(name(1 / 8), 'e')
  t.equal(name(1 / 8 + 1 / 16), 'e.')
  t.equal(name(1 / 8 + 1 / 16 + 1 / 32), 'e..')
  t.equal(name(1 / 16), 's')
  t.equal(name(1 / 16 + 1 / 32), 's.')
  t.equal(name(1 / 16 + 1 / 32 + 1 / 64), 's..')
  t.end()
})
